spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/hoonyong?autoReconnect=true&characterEncoding=utf8&tcpNoDelay=true&socketTimeout=7000&serverTimezone=UTC
    username: cics
    passward: dlsxjspt7510