spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/hoonyong?autoReconnect=true&characterEncoding=utf8&tcpNoDelay=true&socketTimeout=7000&serverTimezone=UTC
    username: root
    password: dlsxjspt7510
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: 1234